---
- hosts: appserver
  user: root
  tasks:
      - name: install the httpd
        yum: name=httpd state=installed
      - name: copy the file index.html
        copy: src=index.html dest=/var/www/html/index.html
        delegate_to: 192.168.199.140
      - name: restart the httpd
        service: name=httpd state=restarted
      - name: install wget
        command: yum remove -y wget
        delegate_to: 192.168.199.141
